import { Wifi, Utensils, WavesLadder } from "lucide-react";

export const rooms = [
  {
    id: 1,
    title: "Deluxe King Room",
    description:
      "Spacious 42m² room with breathtaking sea views from a private balcony.\nFeatures a luxurious king-size bed, modern bathroom with rain shower, and complimentary high-speed Wi-Fi.\nPerfect for couples or solo travelers seeking relaxation and natural beauty",
    images: [
      "https://q-xx.bstatic.com/xdata/images/hotel/max500/553989415.jpg?k=a16fffb6c251786544196d1a6b16f95656f2bd236d0c85aa9d9a93ac183989ab&o=",
      "https://q-xx.bstatic.com/xdata/images/hotel/max500/553989415.jpg?k=a16fffb6c251786544196d1a6b16f95656f2bd236d0c85aa9d9a93ac183989ab&o=",
      "https://q-xx.bstatic.com/xdata/images/hotel/max500/553989415.jpg?k=a16fffb6c251786544196d1a6b16f95656f2bd236d0c85aa9d9a93ac183989ab&o=",
      "https://q-xx.bstatic.com/xdata/images/hotel/max500/553989415.jpg?k=a16fffb6c251786544196d1a6b16f95656f2bd236d0c85aa9d9a93ac183989ab&o=",
    ],
    pricePerNight: 120,
    rating: 4.7,
    maxGuests: 2,
    amenities: [
      { name: "Wi-Fi", icon: "Wifi" },
      { name: "King Bed", icon: "BedDouble" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Air Conditioning", icon: "AirVent" },
    ],
    roomType: "Deluxe",
    size: 32,
    bedType: "King",
    serviceFee: 35,
    cleaningFee: 45,
    hotelName: "LuxHotel Downtown",
    address: "123 Urban Street, Phnom Penh",
  },
  {
    id: 2,
    title: "Standard Twin Room",
    description:
      "Spacious 42m² room with breathtaking sea views from a private balcony.\nFeatures a luxurious king-size bed, modern bathroom with rain shower, and complimentary high-speed Wi-Fi.\nPerfect for couples or solo travelers seeking relaxation and natural beauty",
    images: [
      "https://q-xx.bstatic.com/xdata/images/hotel/max500/553989415.jpg?k=a16fffb6c251786544196d1a6b16f95656f2bd236d0c85aa9d9a93ac183989ab&o=",
      "https://q-xx.bstatic.com/xdata/images/hotel/max500/553989415.jpg?k=a16fffb6c251786544196d1a6b16f95656f2bd236d0c85aa9d9a93ac183989ab&o=",
      "https://q-xx.bstatic.com/xdata/images/hotel/max500/553989415.jpg?k=a16fffb6c251786544196d1a6b16f95656f2bd236d0c85aa9d9a93ac183989ab&o=",
      "https://q-xx.bstatic.com/xdata/images/hotel/max500/553989415.jpg?k=a16fffb6c251786544196d1a6b16f95656f2bd236d0c85aa9d9a93ac183989ab&o=",
    ],
    pricePerNight: 80,
    rating: 4.0,
    maxGuests: 2,
    amenities: [
      { name: "Wi-Fi", icon: "Wifi" },
      { name: "King Bed", icon: "BedDouble" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Air Conditioning", icon: "AirVent" },
    ],
    isAvailable: true,
    roomType: "Standard",
    size: 25,
    bedType: "Twin",
    serviceFee: 40,
    cleaningFee: 50,
    hotelName: "LuxHotel Downtown",
    address: "123 Urban Street, Phnom Penh",
  },
  {
    id: 3,
    title: "Executive Suite",
    description:
      "Spacious 42m² room with breathtaking sea views from a private balcony.\nFeatures a luxurious king-size bed, modern bathroom with rain shower, and complimentary high-speed Wi-Fi.\nPerfect for couples or solo travelers seeking relaxation and natural beauty",
    images: [
      "https://images.mrandmrssmith.com/images/1482x988/5722704-the-royal-sands-koh-rong-koh-rong-koh-rong-island-preah-sihanouk-cambodia.jpg",
      "https://images.mrandmrssmith.com/images/1482x988/5722704-the-royal-sands-koh-rong-koh-rong-koh-rong-island-preah-sihanouk-cambodia.jpg",
      "https://images.mrandmrssmith.com/images/1482x988/5722704-the-royal-sands-koh-rong-koh-rong-koh-rong-island-preah-sihanouk-cambodia.jpg",
      "https://images.mrandmrssmith.com/images/1482x988/5722704-the-royal-sands-koh-rong-koh-rong-koh-rong-island-preah-sihanouk-cambodia.jpg",
    ],
    pricePerNight: 250,
    rating: 4.8,
    maxGuests: 3,
    amenities: [
      { name: "Wi-Fi", icon: "Wifi" },
      { name: "King Bed", icon: "BedDouble" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Air Conditioning", icon: "AirVent" },
    ],
    isAvailable: false,
    roomType: "Suite",
    size: 50,
    bedType: "King",
    serviceFee: 40,
    cleaningFee: 50,
    hotelName: "LuxHotel Downtown",
    address: "123 Urban Street, Phnom Penh",
  },
  {
    id: 4,
    title: "Family Room",
    description:
      "Spacious 42m² room with breathtaking sea views from a private balcony.\nFeatures a luxurious king-size bed, modern bathroom with rain shower, and complimentary high-speed Wi-Fi.\nPerfect for couples or solo travelers seeking relaxation and natural beauty",
    images: [
      "https://assets.hyatt.com/content/dam/hyatt/hyattdam/images/2019/07/12/1258/Park-Hyatt-Siem-Reap-P233-Park-King-Room.jpg/Park-Hyatt-Siem-Reap-P233-Park-King-Room.16x9.jpg?imwidth=1280",
      "https://assets.hyatt.com/content/dam/hyatt/hyattdam/images/2019/07/12/1258/Park-Hyatt-Siem-Reap-P233-Park-King-Room.jpg/Park-Hyatt-Siem-Reap-P233-Park-King-Room.16x9.jpg?imwidth=1280",
      "https://assets.hyatt.com/content/dam/hyatt/hyattdam/images/2019/07/12/1258/Park-Hyatt-Siem-Reap-P233-Park-King-Room.jpg/Park-Hyatt-Siem-Reap-P233-Park-King-Room.16x9.jpg?imwidth=1280",
      "https://assets.hyatt.com/content/dam/hyatt/hyattdam/images/2019/07/12/1258/Park-Hyatt-Siem-Reap-P233-Park-King-Room.jpg/Park-Hyatt-Siem-Reap-P233-Park-King-Room.16x9.jpg?imwidth=1280",
    ],
    pricePerNight: 180,
    rating: 4.2,
    maxGuests: 4,
    amenities: [
      { name: "Wi-Fi", icon: "Wifi" },
      { name: "King Bed", icon: "BedDouble" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Air Conditioning", icon: "AirVent" },
    ],
    isAvailable: true,
    roomType: "Family",
    size: 40,
    bedType: "Queen & Twin",
    serviceFee: 40,
    cleaningFee: 50,
    hotelName: "LuxHotel Downtown",
    address: "123 Urban Street, Phnom Penh",
  },
  {
    id: 5,
    title: "Single Room",
    description:
      "Spacious 42m² room with breathtaking sea views from a private balcony.\nFeatures a luxurious king-size bed, modern bathroom with rain shower, and complimentary high-speed Wi-Fi.\nPerfect for couples or solo travelers seeking relaxation and natural beauty",
    images: [
      "https://dq5r178u4t83b.cloudfront.net/wp-content/uploads/sites/125/2020/06/15182916/Sofitel-Dubai-Wafi-Luxury-Room-Bedroom-Skyline-View-Image1_WEB.jpg",
      "https://dq5r178u4t83b.cloudfront.net/wp-content/uploads/sites/125/2020/06/15182916/Sofitel-Dubai-Wafi-Luxury-Room-Bedroom-Skyline-View-Image1_WEB.jpg",
      "https://dq5r178u4t83b.cloudfront.net/wp-content/uploads/sites/125/2020/06/15182916/Sofitel-Dubai-Wafi-Luxury-Room-Bedroom-Skyline-View-Image1_WEB.jpg",
      "https://dq5r178u4t83b.cloudfront.net/wp-content/uploads/sites/125/2020/06/15182916/Sofitel-Dubai-Wafi-Luxury-Room-Bedroom-Skyline-View-Image1_WEB.jpg",
    ],
    pricePerNight: 60,
    maxGuests: 1,
    amenities: [
      { name: "Wi-Fi", icon: "Wifi" },
      { name: "King Bed", icon: "BedDouble" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Air Conditioning", icon: "AirVent" },
    ],
    isAvailable: true,
    roomType: "Standard",
    size: 20,
    bedType: "Single",
    serviceFee: 40,
    cleaningFee: 50,
    hotelName: "LuxHotel Downtown",
    address: "123 Urban Street, Phnom Penh",
  },
  {
    id: 6,
    title: "Presidential Suite",
    description:
      "Spacious 42m² room with breathtaking sea views from a private balcony.\nFeatures a luxurious king-size bed, modern bathroom with rain shower, and complimentary high-speed Wi-Fi.\nPerfect for couples or solo travelers seeking relaxation and natural beauty",
    images: [
      "https://publish.purewow.net/wp-content/uploads/sites/2/2019/08/grand-velas.jpeg?fit=1360%2C906",
      "https://publish.purewow.net/wp-content/uploads/sites/2/2019/08/grand-velas.jpeg?fit=1360%2C906",
      "https://publish.purewow.net/wp-content/uploads/sites/2/2019/08/grand-velas.jpeg?fit=1360%2C906",
      "https://publish.purewow.net/wp-content/uploads/sites/2/2019/08/grand-velas.jpeg?fit=1360%2C906",
    ],
    pricePerNight: 500,
    rating: 5.0,
    maxGuests: 4,
    amenities: [
      { name: "Wi-Fi", icon: "Wifi" },
      { name: "King Bed", icon: "BedDouble" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Air Conditioning", icon: "AirVent" },
    ],
    isAvailable: false,
    roomType: "Suite",
    size: 80,
    bedType: "King",
    serviceFee: 40,
    cleaningFee: 50,
    hotelName: "LuxHotel Downtown",
    address: "123 Urban Street, Phnom Penh",
  },
  {
    id: 7,
    title: "Superior Double Room",
    description:
      "Spacious 42m² room with breathtaking sea views from a private balcony.\nFeatures a luxurious king-size bed, modern bathroom with rain shower, and complimentary high-speed Wi-Fi.\nPerfect for couples or solo travelers seeking relaxation and natural beauty",
    images: [
      "https://assets.anantara.com/image/upload/q_auto,f_auto,c_limit,w_1045/media/minor/anantara/images/anantara-angkor-resort/accommodation/details-page/suite/anantara_angkor_suite_bedroom_726x392.jpg",
      "https://assets.anantara.com/image/upload/q_auto,f_auto,c_limit,w_1045/media/minor/anantara/images/anantara-angkor-resort/accommodation/details-page/suite/anantara_angkor_suite_bedroom_726x392.jpg",
      "https://assets.anantara.com/image/upload/q_auto,f_auto,c_limit,w_1045/media/minor/anantara/images/anantara-angkor-resort/accommodation/details-page/suite/anantara_angkor_suite_bedroom_726x392.jpg",
    ],
    pricePerNight: 110,
    rating: 4.3,
    maxGuests: 2,
    amenities: [
      { name: "Wi-Fi", icon: "Wifi" },
      { name: "King Bed", icon: "BedDouble" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Air Conditioning", icon: "AirVent" },
    ],
    isAvailable: true,
    roomType: "Superior",
    size: 28,
    bedType: "Double",
    serviceFee: 40,
    cleaningFee: 50,
    hotelName: "LuxHotel Downtown",
    address: "123 Urban Street, Phnom Penh",
  },
  {
    id: 8,
    title: "Economy Room",
    description:
      "Spacious 42m² room with breathtaking sea views from a private balcony.\nFeatures a luxurious king-size bed, modern bathroom with rain shower, and complimentary high-speed Wi-Fi.\nPerfect for couples or solo travelers seeking relaxation and natural beauty",
    images: [
      "https://www.experienceparkhyattsiemreap.com/wp-content/uploads/2023/03/Park-Hyatt-Siem-Reap-SEO-MAR-C01-1.jpg",
      "https://www.experienceparkhyattsiemreap.com/wp-content/uploads/2023/03/Park-Hyatt-Siem-Reap-SEO-MAR-C01-1.jpg",
      "https://www.experienceparkhyattsiemreap.com/wp-content/uploads/2023/03/Park-Hyatt-Siem-Reap-SEO-MAR-C01-1.jpg",
      "https://www.experienceparkhyattsiemreap.com/wp-content/uploads/2023/03/Park-Hyatt-Siem-Reap-SEO-MAR-C01-1.jpg",
    ],
    pricePerNight: 50,
    maxGuests: 2,
    amenities: [
      { name: "Wi-Fi", icon: "Wifi" },
      { name: "King Bed", icon: "BedDouble" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Air Conditioning", icon: "AirVent" },
    ],
    isAvailable: true,
    roomType: "Standard",
    size: 18,
    bedType: "Twin",
    serviceFee: 40,
    cleaningFee: 50,
    hotelName: "LuxHotel Downtown",
    address: "123 Urban Street, Phnom Penh",
  },
  {
    id: 9,
    title: "Honeymoon Suite",
    description:
      "Spacious 42m² room with breathtaking sea views from a private balcony.\nFeatures a luxurious king-size bed, modern bathroom with rain shower, and complimentary high-speed Wi-Fi.\nPerfect for couples or solo travelers seeking relaxation and natural beauty",
    images: [
      "https://www.fcccollection.com/wp-content/uploads/2025/11/fcc_angkor_avani_colonial_pool_access_room_1600x1000_001.png",
      "https://www.fcccollection.com/wp-content/uploads/2025/11/fcc_angkor_avani_colonial_pool_access_room_1600x1000_001.png",
      "https://www.fcccollection.com/wp-content/uploads/2025/11/fcc_angkor_avani_colonial_pool_access_room_1600x1000_001.png",
      "https://www.fcccollection.com/wp-content/uploads/2025/11/fcc_angkor_avani_colonial_pool_access_room_1600x1000_001.png",
    ],
    pricePerNight: 300,
    rating: 4.9,
    maxGuests: 2,
    amenities: [
      { name: "Wi-Fi", icon: "Wifi" },
      { name: "King Bed", icon: "BedDouble" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Air Conditioning", icon: "AirVent" },
    ],
    isAvailable: true,
    roomType: "Suite",
    size: 45,
    bedType: "King",
    serviceFee: 40,
    cleaningFee: 50,
    hotelName: "LuxHotel Downtown",
    address: "123 Urban Street, Phnom Penh",
  },
  {
    id: 10,
    title: "Studio Room",
    description:
      "Spacious 42m² room with breathtaking sea views from a private balcony.\nFeatures a luxurious king-size bed, modern bathroom with rain shower, and complimentary high-speed Wi-Fi.\nPerfect for couples or solo travelers seeking relaxation and natural beauty",
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/575952010.jpg?k=8e7f5060cb8d7238a1dad98a92df197401c6af6c87feb5ade851757415a396d4&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/575952010.jpg?k=8e7f5060cb8d7238a1dad98a92df197401c6af6c87feb5ade851757415a396d4&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/575952010.jpg?k=8e7f5060cb8d7238a1dad98a92df197401c6af6c87feb5ade851757415a396d4&o=",
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/575952010.jpg?k=8e7f5060cb8d7238a1dad98a92df197401c6af6c87feb5ade851757415a396d4&o=",
    ],
    pricePerNight: 90,
    rating: 4.1,
    maxGuests: 2,
    amenities: [
      { name: "Wi-Fi", icon: "Wifi" },
      { name: "King Bed", icon: "BedDouble" },
      { name: "Smart TV", icon: "Tv" },
      { name: "Air Conditioning", icon: "AirVent" },
    ],
    isAvailable: true,
    roomType: "Studio",
    size: 30,
    bedType: "Double",
    serviceFee: 40,
    cleaningFee: 50,
    hotelName: "LuxHotel Downtown",
    address: "123 Urban Street, Phnom Penh",
  },
];

export const categories = [
  { id: "standard", roomType: "Standard Room" },
  { id: "deluxe", roomType: "Deluxe Room" },
  { id: "suite", roomType: "Suite" },
  { id: "family", roomType: "Family Room" },
];

export const amenitiesData = [
  {
    id: "wifi",
    label: "Free Wifi",
    icon: Wifi,
  },
  {
    id: "pool",
    label: "Pool Access",
    icon: WavesLadder,
  },
  {
    id: "breakfast",
    label: "Breakfast Included",
    icon: Utensils,
  },
];

export const bookingDummy = {
  id: "1",
  hotelName: "LuxHotel Downtown",
  imageUrl:
    "url('https://lh3.googleusercontent.com/aida-public/AB6AXuBUAJDfP2oUzxb8Y-osR4JwKsyJFVgIzx8r5VGYiS0T-DRr-XRH0QE5o4IKUHwBZ4ZhqXTWPBRi-7YEu7BvbeX7u39FtjjgFh2qazAeCDYGKiHrqTPfBrJBiB880PB7wKeD1rGQUBMxhWOPtE21cNHCC9YH7GQSSoSuNoBIt96UfzqcInQBJx6A4Ih1EMGV2BmTVWntYZWttbDv3fE5GFqPLlosVAF7qUM4bNCyc5fcxkW7kvFRLICf8eCMP09EjnlKxOq7JlqoswY')",
  address: "123 Main St, New York, NY",
  roomType: "Deluxe Room",
  // export const bookingDummy: BookingSummary = {
  //   hotelName: "LuxHotel Downtown",
  //   imageUrl:
  //     "url('https://lh3.googleusercontent.com/aida-public/AB6AXuBUAJDfP2oUzxb8Y-osR4JwKsyJFVgIzx8r5VGYiS0T-DRr-XRH0QE5o4IKUHwBZ4ZhqXTWPBRi-7YEu7BvbeX7u39FtjjgFh2qazAeCDYGKiHrqTPfBrJBiB880PB7wKeD1rGQUBMxhWOPtE21cNHCC9YH7GQSSoSuNoBIt96UfzqcInQBJx6A4Ih1EMGV2BmTVWntYZWttbDv3fE5GFqPLlosVAF7qUM4bNCyc5fcxkW7kvFRLICf8eCMP09EjnlKxOq7JlqoswY')",
  //   address: "123 Main St, New York, NY",
  //   roomType: "Deluxe Room",
  //   checkIn: {
  //     date: "Thu, Oct 12, 2023",
  //     time: "After 3:00 PM",
  //   },
  //   checkOut: {
  //     date: "Sun, Oct 15, 2023",
  //     time: "Before 11:00 AM",
  //   },
  //   nights: 3,
  //   guests: 2,
  //   pricePerNight: 200,
  //   taxes: 50,
  //   discount: 0,
  // };
};

export const RoomBooking = {
  id: 1,
  title: "Deluxe Ocean View",
  description: "Beautiful sea view with private balcony",
  images: [
    "https://q-xx.bstatic.com/xdata/images/hotel/max500/553989415.jpg?k=a16fffb6c251786544196d1a6b16f95656f2bd236d0c85aa9d9a93ac183989ab&o=",
  ],
  pricePerNight: 185,
  rating: 4.8,
  maxGuests: 3,
  amenities: [],
  roomType: "Deluxe",
  size: 42,
  bedType: "King",

  nights: 4,
  taxes: 68,
  discount: 45,
  guests: 2,
  address: "123 Ocean Drive, Seminyak, Bali",

  checkIn: {
    date: "2026-02-15",
    time: "14:00",
  },
  checkOut: {
    date: "2026-02-19",
    time: "12:00",
  },

  // nights: 3,
  // guests: 2,
  // pricePerNight: 200,
  // taxes: 50,
  // discount: 0,
  status: "cancelled",
};

export const statusConfig = {
  upcoming: {
    label: "Upcoming",
    badge: "bg-green-100 text-green-700",
    primaryAction: "Manage",
  },
  completed: {
    label: "Completed",
    badge: "bg-gray-100 text-gray-700",
    primaryAction: "Book Again",
  },
  cancelled: {
    label: "Cancelled",
    badge: "bg-red-100 text-red-700",
    primaryAction: "View Details",
  },
};
export const bookingSummaries = [
  {
    id: "1",
    hotelName: "Grand Horizon Resort",
    imageUrl:
      "https://media.gettyimages.com/id/2168152526/video/night-view-of-downtown-chicago-skyscrapers-from-the-chicago-river-illinois.jpg?s=640x640&k=20&c=CSY0KOTamsUedP6BxcNz_BRZZs3u0603eVPs7_07vvo=",
    roomType: "Deluxe Ocean View",
    address: "Malibu, California, USA",
    checkIn: { date: "2023-10-12", time: "14:00" },
    checkOut: { date: "2023-10-15", time: "11:00" },
    nights: 3,
    guests: 2,
    pricePerNight: 150,
    taxes: 45,
    discount: 30,
    status: "upcoming",
  },
  {
    id: "2",
    hotelName: "Skyline City Hotel",
    imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    roomType: "Executive King Room",
    address: "New York City, USA",
    checkIn: { date: "2023-11-02", time: "15:00" },
    checkOut: { date: "2023-11-05", time: "11:00" },
    nights: 3,
    guests: 2,
    pricePerNight: 220,
    taxes: 65,
    discount: 40,
    status: "completed",
  },
  {
    id: "3",
    hotelName: "Palm Breeze Boutique",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    roomType: "Garden Suite",
    address: "Phuket, Thailand",
    checkIn: { date: "2023-12-10", time: "14:00" },
    checkOut: { date: "2023-12-14", time: "11:00" },
    nights: 4,
    guests: 2,
    pricePerNight: 120,
    taxes: 50,
    discount: 20,
    status: "cancelled",
  },
  {
    id: "4",
    hotelName: "Aurora Mountain Lodge",
    imageUrl:
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/665858808.jpg?k=d77877133bf1e31fa99799550d2e7bc7048a85b77e34babfa37b996d59cc4df4&o=",
    roomType: "Chalet with Fireplace",
    address: "Zermatt, Switzerland",
    checkIn: { date: "2024-01-18", time: "15:00" },
    checkOut: { date: "2024-01-22", time: "10:00" },
    nights: 4,
    guests: 4,
    pricePerNight: 340,
    taxes: 120,
    discount: 80,
    status: "cancelled",
  },
  {
    id: "5",
    hotelName: "Sunset Bay Resort",
    imageUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    roomType: "Family Sea View Room",
    address: "Bali, Indonesia",
    checkIn: { date: "2024-02-05", time: "14:00" },
    checkOut: { date: "2024-02-09", time: "11:00" },
    nights: 4,
    guests: 3,
    pricePerNight: 180,
    taxes: 70,
    discount: 50,
    status: "cancelled",
  },
  {
    id: "6",
    hotelName: "Sunset Bay Resort",
    imageUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    roomType: "Family Sea View Room",
    address: "Bali, Indonesia",
    checkIn: { date: "2024-02-05", time: "14:00" },
    checkOut: { date: "2024-02-09", time: "11:00" },
    nights: 4,
    guests: 3,
    pricePerNight: 180,
    taxes: 70,
    discount: 50,
    status: "cancelled",
  },
  
];
export const users = [
  {
    id: 1,
    name: 'John Doe',
    userId: 'USR-001',
    avatar: 'https://i.pravatar.cc/150?img=1',
    role: 'Admin',
    email: 'john@example.com',
    status: 'Active',
    joined: 'Jan 10, 2025',
  },
  {
    id: 2,
    name: 'Sarah Smith',
    userId: 'USR-002',
    avatar: 'https://i.pravatar.cc/150?img=2',
    role: 'Manager',
    email: 'sarah@example.com',
    status: 'Inactive',
    joined: 'Feb 02, 2025',
  },
  {
    id: 3,
    name: 'Michael Lee',
    userId: 'USR-003',
    avatar: 'https://i.pravatar.cc/150?img=3',
    role: 'Staff',
    email: 'michael@example.com',
    status: 'Pending',
    joined: 'Mar 18, 2025',
  },
];

