export const rooms = [
  {
    id: "1",
    title: "Deluxe King Room",
    description: "Spacious room with a king-size bed and city view.",
    images: [
      "https://www.myboutiquehotel.com/photos/114329/the-royal-sands-koh-rong-koh-rong-island-056-1697543189-728x400.jpg",
    ],
    pricePerNight: 120,
    rating: 4.5,
    maxGuests: 2,
    amenities: ["WiFi", "Breakfast", "Single Bed", "TV"],
    isAvailable: true,
    roomType: "Deluxe",
    size: 30,
    bedType: "King",
  },
  {
    id: "2",
    title: "Standard Twin Room",
    description: "Comfortable room with two single beds, ideal for friends.",
    images: [
      "https://q-xx.bstatic.com/xdata/images/hotel/max500/553989415.jpg?k=a16fffb6c251786544196d1a6b16f95656f2bd236d0c85aa9d9a93ac183989ab&o=",
    ],
    pricePerNight: 80,
    rating: 4.0,
    maxGuests: 2,
    amenities: ["WiFi", "Breakfast", "King Bed"],
    isAvailable: true,
    roomType: "Standard",
    size: 25,
    bedType: "Twin",
  },
  {
    id: "3",
    title: "Executive Suite",
    description: "Luxurious suite with separate living area and king bed.",
    images: [
      "https://images.mrandmrssmith.com/images/1482x988/5722704-the-royal-sands-koh-rong-koh-rong-koh-rong-island-preah-sihanouk-cambodia.jpg",
    ],
    pricePerNight: 250,
    rating: 4.8,
    maxGuests: 3,
    amenities: ["WiFi", "Breakfast", "Queen Bed", "TV", "Air Conditioning"],
    isAvailable: false,
    roomType: "Suite",
    size: 50,
    bedType: "King",
  },
  {
    id: "4",
    title: "Family Room",
    description: "Spacious room suitable for a family of 4 with two beds.",
    images: [
      "https://assets.hyatt.com/content/dam/hyatt/hyattdam/images/2019/07/12/1258/Park-Hyatt-Siem-Reap-P233-Park-King-Room.jpg/Park-Hyatt-Siem-Reap-P233-Park-King-Room.16x9.jpg?imwidth=1280",
    ],
    pricePerNight: 180,
    rating: 4.2,
    maxGuests: 4,
    amenities: ["WiFi", "Breakfast", "Double Bed", "Air Conditioning"],
    isAvailable: true,
    roomType: "Family",
    size: 40,
    bedType: "Queen & Twin",
  },
  {
    id: "5",
    title: "Single Room",
    description: "Cozy room for solo travelers with basic amenities.",
    images: [
      "https://dq5r178u4t83b.cloudfront.net/wp-content/uploads/sites/125/2020/06/15182916/Sofitel-Dubai-Wafi-Luxury-Room-Bedroom-Skyline-View-Image1_WEB.jpg",
    ],
    pricePerNight: 60,
    maxGuests: 1,
    amenities: ["WiFi", "Breakfast", "King"],
    isAvailable: true,
    roomType: "Standard",
    size: 20,
    bedType: "Single",
  },
  {
    id: "6",
    title: "Presidential Suite",
    description: "Top-tier suite with panoramic views and premium services.",
    images: [
      "https://publish.purewow.net/wp-content/uploads/sites/2/2019/08/grand-velas.jpeg?fit=1360%2C906",
    ],
    pricePerNight: 500,
    rating: 5.0,
    maxGuests: 4,
    amenities: [
      "WiFi",
      "Breakfast",
      "Mini Bar",
      "TV",
      "Air Conditioning",
      "Jacuzzi",
    ],
    isAvailable: false,
    roomType: "Suite",
    size: 80,
    bedType: "King",
  },
  {
    id: "7",
    title: "Superior Double Room",
    description: "Modern room with a double bed and city view.",
    images: [
      "https://assets.anantara.com/image/upload/q_auto,f_auto,c_limit,w_1045/media/minor/anantara/images/anantara-angkor-resort/accommodation/details-page/suite/anantara_angkor_suite_bedroom_726x392.jpg",
    ],
    pricePerNight: 110,
    rating: 4.3,
    maxGuests: 2,
    amenities: ["WiFi", "Breakfast", "Single Bed", "Air Conditioning"],
    isAvailable: true,
    roomType: "Superior",
    size: 28,
    bedType: "Double",
  },
  {
    id: "8",
    title: "Economy Room",
    description: "Affordable room with essential facilities for travelers.",
    images: [
      "https://www.experienceparkhyattsiemreap.com/wp-content/uploads/2023/03/Park-Hyatt-Siem-Reap-SEO-MAR-C01-1.jpg",
    ],
    pricePerNight: 50,
    maxGuests: 2,
    amenities: ["WiFi", "Breakfast", "King"],
    isAvailable: true,
    roomType: "Standard",
    size: 18,
    bedType: "Twin",
  },
  {
    id: "9",
    title: "Honeymoon Suite",
    description: "Romantic suite for couples with luxurious amenities.",
    images: [
      "https://www.fcccollection.com/wp-content/uploads/2025/11/fcc_angkor_avani_colonial_pool_access_room_1600x1000_001.png",
    ],
    pricePerNight: 300,
    rating: 4.9,
    maxGuests: 2,
    amenities: ["WiFi", "Breakfast", "Double Bed", "TV", "Air Conditioning"],
    isAvailable: true,
    roomType: "Suite",
    size: 45,
    bedType: "King",
  },
  {
    id: "10",
    title: "Studio Room",
    description: "Compact studio room with a kitchenette for extended stays.",
    images: [
      "https://cf.bstatic.com/xdata/images/hotel/max1024x768/575952010.jpg?k=8e7f5060cb8d7238a1dad98a92df197401c6af6c87feb5ade851757415a396d4&o=",
    ],
    pricePerNight: 90,
    rating: 4.1,
    maxGuests: 2,
    amenities: ["WiFi", "TV", "Queen Bed"],
    isAvailable: true,
    roomType: "Studio",
    size: 30,
    bedType: "Double",
  },
];

export const categories = [
  { id: "standard", roomType: "Standard Room" },
  { id: "deluxe", roomType: "Deluxe Room" },
  { id: "suite", roomType: "Suite" },
  { id: "family", roomType: "Family Room" },
];
