name: Notify Telegram on Push

on:
  push:
    branches:
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        run: |
          curl -s -X POST "https://api.telegram.org/bot8226854415:AAGCdipmCSKliF-pfMnMjsDU8XfFwqfHtGM/sendMessage" \
          -d chat_id="-5069468471" \
          -d text="🚀 New push to repository: ${{ github.repository }}\n👤 By: ${{ github.actor }}\n📝 Commit message: ${{ github.event.head_commit.message }}"
